### ISSUE TITLE
not running Get ".txt": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by hassankhan98** [theinfosecguy/QuickXSS#7]
any solution?

![Screen Shot 2021-03-10 at 7 34 51 PM](https://user-images.githubusercontent.com/33081303/110645718-09aa3200-81d8-11eb-908f-b3148063d7d4.png)

**Comment by theinfosecguy** [comment]
@hassankhan98 Can you share the command you are using along with the OS?

**Comment by hassankhan98** [comment]
./QuickXSS.sh -d infracloud.io

OS ==> Mac

**Comment by hassankhan98** [comment]
......

**Comment by pavanreddi** [comment]
Hi Sir, 
Good day 

Facing similar issue can you please help

[*] 🦊 Start scan [SID:0][0/1][0.00%%] / URL: .txt
[E] not running Get ".txt": unsupported protocol scheme ""

using 64 bit Kali verified all dependencies still issue persist. Thanks in advance have a wonderful day :)

**Comment by theinfosecguy** [comment]
Hey @pavanreddi @hassankhan98 ,

Sorry for the issues. I am working on a fix , Will release it soon.

**Comment by theinfosecguy** [comment]
Hey @pavanreddi @hassankhan98 

I have fixed the issue, Can you reclone & Check once again?

**Comment by pavanreddi** [comment]
Thanks for your time. runs perfectly without any issues :)

**Comment by hassankhan98** [comment]
Thanks Bro 

working now .....

**Comment by ghanashyam924** [comment]
Hello Sir,

Facing similar issue can you please help:

[*] 🦊 Start scan [SID:3][3/69][4.35%%] / URL: recated.com
[E] not running Get "recated.com": unsupported protocol scheme ""

Using 64 bit Kali & Browser Version 78.7.0esr

Regards,
Mrghannu

**Comment by theinfosecguy** [comment]
Hey,

I'm working on a fix.
